'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const translations: Record<Language, Record<string, string>> = {
    en: {
      nav_home: 'Home',
      nav_about: 'About',
      nav_rooms: 'Rooms',
      nav_amenities: 'Amenities',
      nav_location: 'Location',
      nav_trust: 'Trust Committee',
      nav_contact: 'Contact',
      nav_temple: 'The Temple',
      nav_book: 'Enquire Now',
      hero_title: 'Experience Spiritual Serenity at the Heart of Chittorgarh',
      hero_sub: 'Welcome to Jain Dharamsala, where tradition meets comfort. Enjoy a peaceful stay with modern amenities and authentic Jain cuisine.',
      book_checkin: 'Check In',
      book_checkout: 'Check Out',
      book_guests: 'Guests',
      book_btn: 'Check Availability',
      about_title: 'About Jain Dharamsala',
      about_history: 'History & Heritage',
      about_facilities: 'Our Facilities',
      amenities_title: 'Everything You Need',
      footer_address: 'Chittorgarh Fort Road, Chittorgarh, Rajasthan.',
      footer_contact: 'Contact',
      footer_links: 'Quick Links',
      amenity_rooms: 'Spacious Rooms',
      amenity_ac: 'Air Conditioning',
      amenity_water: 'Hot Water',
      amenity_dining: 'Dining Hall',
      amenity_wifi: 'Free Wi-Fi',
      amenity_parking: 'Parking Space',
      site_name: 'Jain Dharamsala',
      site_sub: 'Chittorgarh',
      copyright_rights: 'All rights reserved.',
      made_with: 'Made with',
      by: 'by',
      guest_1: '1 Person',
      guest_2: '2 Persons',
      guest_3: '3+ Persons',
      guest_family: 'Family Room',
      info_best_price: 'Best Price Guaranteed',
      info_verified: 'Verified Stay',
      info_jain_food: 'Jain Food Available',
      footer_copyright: 'Jain Dharamsala Chittorgarh. All rights reserved.',
      trust_title: 'Trust Committee',
      trust_subtitle: 'Members dedicated to the service of the society.',
      trust_president: 'President',
      trust_secretary: 'Secretary',
      trust_treasurer: 'Treasurer',
      trust_all_members: 'All Members',
      trust_col_sn: 'S.No.',
      trust_col_name: 'Name',
      trust_col_city: 'Village/City',
      trust_dr_al_jain: 'Dr. A. L. Jain',
      trust_rakesh_jain: 'Mr. Rakesh Kumar Jain',
      trust_kanhaiyalal: 'Mr. Kanhaiyalal Chhajed',
      trust_member_1: 'Mr. Nareshbhai Amritlalji Shah',
      trust_city_mumbai: 'Mumbai',
      trust_member_2: 'Mr. Kalpesh Bhai Vanmalidasji Shah',
      trust_city_ahmedabad: 'Ahmedabad',
      trust_member_3: 'Mr. Sushil Bhai Narendra Bhai Shah',
      trust_member_4: 'Mr. Mayank Bhai Praveenchand Ji Shah',
      trust_member_5: 'Mr. Sanjay Bhai Amritlal Ji Shah',
      trust_member_6: 'Mr. Anandilal Ji Nagauri',
      trust_city_chittorgarh: 'Chittorgarh',
      trust_member_7: 'Mr. Rakesh Kumar Ji Ghiya',
      trust_member_8: 'Mr. Shantilalji Rathore',
      trust_member_9: 'Mr. Jivraj Ji Khatod',
      trust_member_10: 'Mr. Manoharlalji Mehta',
      trust_member_11: 'Mr. K. M. Jain',
      trust_member_12: 'Mr. Onkar Singh Babel',
      trust_member_13: 'Mr. Mukesh Kumar Mahatma',
      trust_member_14: 'Mr. Praveen Jain',
      contact_title: 'Contact Us',
      contact_greeting: 'Jai Jinendra. Please feel free to reach out via phone or email.',
      contact_warning_title: 'Warning',
      contact_warning_text: '"Phone numbers of Jain Dharamsala, operated by Shri Jain Shwetambar Saatbees Devari Fort Tirtha Trust Chittorgarh, are listed differently on Google search every day. These numbers are wrongly changed by hackers. People who call on the numbers given by hackers are being cheated, so it is requested to all the people not to pay money for room booking on any number."',
      contact_info_title: 'Information',
      contact_info_text: 'Jain Shwetambar Vishranti Grah is available in front of the railway station with AC room facilities, catering and luxury services. There are also 9 rooms available at Chittorgarh Fort with regular catering and dining facilities.',
      contact_phone_primary: 'Primary Phone',
      contact_rajendra: 'Mr. Rajendra Kachhala',
      timeline_1946: '1946',
      timeline_1946_title: 'Land Acquisition',
      timeline_1946_desc: 'Land for the current Dharamsala complex was purchased under the vision of Acharya Sri Vijayaniti Surishwar Ji.',
      timeline_1948: '1948',
      timeline_1948_title: 'Initial Completion',
      timeline_1948_desc: 'Construction of 9 rooms, 6 cubicles, 1 hall, and 7 shops completed under Kalyanji Anandji Pedhi.',
      timeline_1992: '1992',
      timeline_1992_title: 'Trust Expansion',
      timeline_1992_desc: 'New trust board took over. Added 5 premium rooms, 1 hall, and a dining room.',
      timeline_1998: '1998',
      timeline_1998_title: 'Bhojanshala Opening',
      timeline_1998_desc: 'A massive 60x60 Bhojanshala (Dining Hall) was constructed at the Station Road location.',
      timeline_2003: '2003',
      timeline_2003_title: 'The Great Rejuvenation',
      timeline_2003_desc: 'Leadership under Sri Kanhaiyalal Mahatma added 35 new rooms (11 AC) and modernized the facility.',
      timeline_2009: '2009',
      timeline_2009_title: 'Fort Bhojanshala',
      timeline_2009_desc: 'The dining hall at Saat Bees Devri Temple on the Fort was completed for pilgrims staying on the hill.',
      timeline_today: 'Today',
      timeline_today_title: 'A Premier Sanctuary',
      timeline_today_desc: 'A modern, soulful destination for travelers and sacred events in the heart of Chittorgarh.',
      temple_title: 'Shri Shwetambar Saat Bees Deori Temple',
      temple_subtitle: 'A 15th-Century Architectural Marvel in the Crown of Chittorgarh',
      temple_hist_1: 'The Saat Bees Deori Temple is the most significant Jain pilgrimage site within the Chittorgarh Fort. Originally constructed in the 15th century, this temple complex is a masterpiece of marble carving and Jain architecture.',
      temple_hist_2: 'The name "Saat Bees" (7 and 20) refers to the 27 auxiliary shrines (Devris) that surround the main sanctum. Each shrine is beautifully carved, depicting the Tirthankaras and scenes from Jain mythology.',
      temple_arch_title: 'Divine Architecture',
      temple_arch_text: 'The temple features intricate "Jali" work, vaulted ceilings, and pillars that tell stories of devotion and precision. The main deity, Lord Adinath, presides over the sanctum in a serene marble idol.',
      temple_restoration_title: 'Restoration & Legacy',
      temple_restoration_text: 'The temple has been carefully preserved and restored by the Shri Shwetambar Saat Bees Devari Fort Tirtha Trust, ensuring that the ancient marble work remains a beacon of spirituality for future generations.',
      temple_legend_title: 'Legend & Lore',
      temple_legend_text: 'Local tradition whispers that the main idol of Lord Adinath was found buried under the fort walls, and the temple was built on the very spot where it was discovered. The 27 shrines represent the constellations (Nakshatras), aligning the spiritual realm with the celestial world.',
      temple_fact_1_title: '15th Century',
      temple_fact_1_text: 'Built during the reign of Rana Kumbha, a golden era of Rajasthani architecture.',
      temple_fact_2_title: '27 Shrines',
      temple_fact_2_text: 'Intricately carved auxiliary temples representing the 27 Tirthankaras and constellations.',
      temple_fact_3_title: 'White Marble',
      temple_fact_3_text: 'Pure Makrana marble that glows with a golden hue during sunset.',
      sewa_title: 'Sewa & Pooja Booking',
      sewa_desc: 'Pre-book religious ceremonies and meals.',
      sewa_navkarsi: 'Navkarsi (Breakfast)',
      sewa_bhojanshala: 'Bhojanshala (Full Meal)',
      sewa_pooja: 'Special Pooja',
      booking_confirm_msg: 'Booking request submitted successfully!',
      cal_dharmic_title: 'Dharmic Calendar',
      cal_dharmic_subtitle: 'Sacred Tithis & Bhojanshala Timings',
      cal_ashtami: 'Ashtami',
      cal_chaturdashi: 'Chaturdashi',
      cal_kalyanak: 'Tirthankar Kalyanaks',
      cal_timing_bhojan: 'Bhojanshala: 10:00 AM - 1:00 PM',
      cal_timing_navkarsi: 'Navkarsi: 8:00 AM - 9:30 AM',
      cal_timing_special: 'Special Rasoi',
      cal_view_details: 'View Sacred Details',
    },
    hi: {
      nav_home: 'होम',
      nav_about: 'हमारे बारे में',
      nav_rooms: 'कमरे',
      nav_amenities: 'सुविधाएं',
      nav_location: 'स्थान',
      nav_trust: 'ट्रस्ट समिति',
      nav_contact: 'संपर्क',
      nav_temple: 'मंदिर',
      nav_book: 'पूछताछ करें',
      hero_title: 'चित्तौड़गढ़ के केंद्र में आध्यात्मिक शांति का अनुभव करें',
      hero_sub: 'जैन धर्मशाला में आपका स्वागत है, जहाँ परंपरा और आराम का मिलन होता है। आधुनिक सुविधाओं और प्रमाणिक जैन भोजन के साथ शांतिपूर्ण प्रवास का आनंद लें।',
      book_checkin: 'चेक इन',
      book_checkout: 'चेक आउट',
      book_guests: 'अतिथि',
      book_btn: 'उपलब्धता जांचें',
      about_title: 'जैन धर्मशाला के बारे में',
      about_history: 'इतिहास और विरासत',
      about_facilities: 'हमारी सुविधाएं',
      amenities_title: 'आपकी ज़रूरत की हर चीज़',
      footer_address: 'चित्तौड़गढ़ किला रोड, चित्तौड़गढ़, राजस्थान।',
      footer_contact: 'संपर्क',
      footer_links: 'त्वरित लिंक',
      amenity_rooms: 'हवादार कमरे',
      amenity_ac: 'वातानुकूलित',
      amenity_water: 'गर्म पानी',
      amenity_dining: 'भोजनशाला',
      amenity_wifi: 'फ्री वाई-फाई',
      amenity_parking: 'पार्किंग स्थल',
      site_name: 'जैन धर्मशाला',
      site_sub: 'चित्तौड़गढ़',
      copyright_rights: 'सर्वाधिकार सुरक्षित।',
      made_with: 'निर्मित',
      by: 'द्वारा',
      guest_1: '1 व्यक्ति',
      guest_2: '2 व्यक्ति',
      guest_3: '3+ व्यक्ति',
      guest_family: 'पार्िवारिक कमरा',
      info_best_price: 'सर्वोत्तम मूल्य की गारंटी',
      info_verified: 'सत्यापित प्रवास',
      info_jain_food: 'जैन भोजन उपलब्ध',
      footer_copyright: 'जैन धर्मशाला चित्तौड़गढ़। सर्वाधिकार सुरक्षित।',
      trust_title: 'ट्रस्ट समिति',
      trust_subtitle: 'समाज की सेवा को समर्पित सदस्य।',
      trust_president: 'अध्यक्ष',
      trust_secretary: 'सचिव',
      trust_treasurer: 'कोषाध्यक्ष',
      trust_all_members: 'सभी सदस्य',
      trust_col_sn: 'क्र.सं.',
      trust_col_name: 'नाम',
      trust_col_city: 'गाँव/शहर',
      trust_dr_al_jain: 'डॉ ए. एल. जैन',
      trust_rakesh_jain: 'श्री राकेश कुमार जैन',
      trust_kanhaiyalal: 'श्री कन्हैयालाल छाजेड़',
      trust_member_1: 'श्री नरेशभाई अमृतलालजी शाह',
      trust_city_mumbai: 'मुम्बई',
      trust_member_2: 'श्री कल्पेश भाई वनमालीदासजी शाह',
      trust_city_ahmedabad: 'अहमदाबाद',
      trust_member_3: 'श्री सुशील भाई नरेन्द्र भाई शाह',
      trust_member_4: 'श्री मयंक भाई प्रवीणचन्द जी शाह',
      trust_member_5: 'श्री संजय भाई अमृतलाल जी शाह',
      trust_member_6: 'श्री आन्नदीलाल जी नागौरी',
      trust_city_chittorgarh: 'चित्तौड़गढ़',
      trust_member_7: 'श्री राकेश कुमार जी घीया',
      trust_member_8: 'श्री शांतीलालजी राठौड़',
      trust_member_9: 'श्री जीवराज जी खटोड़',
      trust_member_10: 'श्री मनोहरलालजी मेहता',
      trust_member_11: 'श्री के. एम. जैन',
      trust_member_12: 'श्री औंकार सिंह बाबेल',
      trust_member_13: 'श्री मुकेश कुमार महात्मा',
      trust_member_14: 'श्री प्रवीण Jain',
      contact_title: 'संपर्क करें',
      contact_greeting: 'जय जिनेन्द्र। कृपया पधारें या ईमेल के माध्यम से संपर्क करें।',
      contact_warning_title: 'चेतावनी',
      contact_warning_text: '"श्री जैन श्वेताम्बर सातबीस देवरी किला तीर्थ ट्रस्ट चित्तौड़गढ़ द्वारा संचालित जैन धर्मशाला को फोन नम्बर गूगल सर्च पर रोज अलग अलग नम्बर लिखा हुआ है। यह नम्बर गलत तरीके से हैकर द्वारा बदला गया है। जो लोग हैकर द्वारा दिए गये नम्बर पर रूम बुकिंग के लिए फोन करते है उनके साथ धोखाधड़ी हो रही है, इसलिए सभी लोगो से निवेदन है कि किसी भी नम्बर पर बुकिंग के लिए रुपयों का भुगतान ना करें"',
      contact_info_title: 'सूचना',
      contact_info_text: 'जैन श्वेताम्बर विश्रान्ति गृह रेलवे स्टेशन के सामने चित्तौड़गढ़ में एसी सुविधा वाले कमरों के साथ नवकारसी एवं भोजनशाला की अत्युत्तम सुविधा उपलब्ध है। चित्तौड़गढ़ किले पर भी 9 कमरे व नियमित नवकारसी एवं भोजनशाला की सुविधा उपलब्ध है।',
      contact_phone_primary: 'प्रायमरी फोन',
      contact_rajendra: 'श्री राजेन्द्र कच्छाला',
      timeline_1946: '1946',
      timeline_1946_title: 'भूमि अधिग्रहण',
      timeline_1946_desc: 'आचार्य श्री विजयनीति सूरीश्वर जी म.सा. की प्रेरणा से वर्तमान धर्मशाला परिसर की भूमि क्रय की गई।',
      timeline_1948: '1948',
      timeline_1948_title: 'प्रथम निर्माण पूर्ण',
      timeline_1948_desc: '9 कमरे, 6 कोठरियाँ, 1 हाॅल व 7 दुकानों का निर्माण कार्य पूर्ण हुआ।',
      timeline_1992: '1992',
      timeline_1992_title: 'ट्रस्ट विस्तार',
      timeline_1992_desc: 'नये ट्रस्ट मंडल ने कार्यभार संभाला। 5 कमरे, 1 हाल व भोजनशाला का निर्माण कराया गया।',
      timeline_1998: '1998',
      timeline_1998_title: 'भोजनशाला शुभारंभ',
      timeline_1998_desc: 'स्टेशन रोड पर 60x60 क्षेत्रफल की विशाल एवं सुंदर भोजनशाला का निर्माण पूर्ण हुआ।',
      timeline_2003: '2003',
      timeline_2003_title: 'कायाकल्प अभियान',
      timeline_2003_desc: 'श्री कन्हैयालाल जी महात्मा के नेतृत्व में 35 नये कमरों (11 ए.सी.) की अभिवृद्धि हुई।',
      timeline_2009: '2009',
      timeline_2009_title: 'किला भोजनशाला',
      timeline_2009_desc: 'सात बीस देवरी मंदिर (किला) में भोजनशाला का कार्य संपन्न हुआ एवं नियमित रूप से चालू हुई।',
      timeline_today: 'आज',
      timeline_today_title: 'नगर की श्रेष्ठ व्यवस्था',
      timeline_today_desc: 'नगर की श्रेष्ठ व्यवस्थाओं वाली जगह, जो यात्रिगणों के साथ विवाह और सामाजिक आयोजनों के लिए प्रसिद्ध है।',
      temple_title: 'श्री श्वेताम्बर सात बीस देवरी मंदिर',
      temple_subtitle: 'चित्तौड़गढ़ के मुकुट में 15वीं शताब्दी का स्थापत्य चमत्कार',
      temple_hist_1: 'सात बीस देवरी मंदिर चित्तौड़गढ़ किले के भीतर सबसे महत्वपूर्ण जैन तीर्थ स्थल है। मूल रूप से 15वीं शताब्दी में निर्मित, यह मंदिर परिसर संगमरमर की नक्काशी और जैन वास्तुकला का एक उत्कृष्ट नमूना है।',
      temple_hist_2: '"सात बीस" (7 और 20) नाम मुख्य गर्भगृह के चारों ओर स्थित 27 सहायक मंदिरों (देवरी) को संदर्भित करता है। प्रत्येक देवरी को खूबसूरती से उकेरा गया है, जिसमें तीर्थंकरों और जैन पौराणिक कथाओं के दृश्यों को दर्शाया गया है।',
      temple_arch_title: 'दिव्य वास्तुकला',
      temple_arch_text: 'मंदिर में जटिल "जाली" का काम, गुंबददार छतें और स्तंभ हैं जो भक्ति और सटीकता की कहानियां सुनाते हैं। मुख्य देवता, भगवान आदिनाथ, गर्भगृह में एक शांत संगमरमर की मूर्ति में विराजमान हैं।',
      temple_restoration_title: 'जीर्णोद्धार और विरासत',
      temple_restoration_text: 'मंदिर को श्री श्वेताम्बर सात बीस देवरी किला तीर्थ ट्रस्ट द्वारा सावधानीपूर्वक संरक्षित और पुनर्स्थापित किया गया है, जिससे यह सुनिश्चित होता है कि प्राचीन संगमरमर का काम भविष्य की पीढ़ियों के लिए आध्यात्मिकता का प्रतीक बना रहे।',
      temple_legend_title: 'किंवदंती और कथा',
      temple_legend_text: 'स्थानीय परंपरा कहती है कि भगवान आदिनाथ की मुख्य मूर्ति किले की दीवारों के नीचे दबी हुई मिली थी, और मंदिर उसी स्थान पर बनाया गया था जहाँ वह मिली थी। 27 देवरियां नक्षत्रों का प्रतिनिधित्व करती हैं, जो आध्यात्मिक जगत को खगोलीय दुनिया के साथ जोड़ती हैं।',
      temple_fact_1_title: '15वीं शताब्दी',
      temple_fact_1_text: 'राणा कुंभा के शासनकाल के दौरान निर्मित, जो राजस्थानी वास्तुकला का स्वर्ण युग था।',
      temple_fact_2_title: '27 देवरियां',
      temple_fact_2_text: '27 तीर्थंकरों और नक्षत्रों का प्रतिनिधित्व करने वाले जटिल नक्काशीदार सहायक मंदिर।',
      temple_fact_3_title: 'सफेद संगमरमर',
      temple_fact_3_text: 'शुद्ध मकराना संगमरमर जो सूर्यास्त के दौरान सुनहरी आभा के साथ चमकता है।',
      sewa_title: 'सेवा और पूजा बुकिंग',
      sewa_desc: 'धार्मिक समारोहों और भोजन की अग्रिम बुकिंग करें।',
      sewa_navkarsi: 'नवकारसी (नाश्ता)',
      sewa_bhojanshala: 'भोजनशाला (पूर्ण भोजन)',
      sewa_pooja: 'विशेष पूजा',
      booking_confirm_msg: 'बुकिंग अनुरोध सफलतापूर्वक सबमिट किया गया!',
      cal_dharmic_title: 'धार्मिक कैलेंडर',
      cal_dharmic_subtitle: 'पवित्र तिथियां और भोजनशाला का समय',
      cal_ashtami: 'अष्टमी',
      cal_chaturdashi: 'चतुर्दशी',
      cal_kalyanak: 'तीर्थंकर कल्याणक',
      cal_timing_bhojan: 'भोजनशाला: प्रातः 10:00 - दोपहर 1:00',
      cal_timing_navkarsi: 'नवकारसी: प्रातः 8:00 - 9:30',
      cal_timing_special: 'विशेष रसोई',
      cal_view_details: 'पवित्र विवरण देखें',
    },
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
