'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const translations: Record<Language, Record<string, string>> = {
    en: {
      nav_home: 'Home',
      nav_about: 'About',
      nav_history: 'History',
      nav_rooms: 'Rooms',
      nav_amenities: 'Amenities',
      nav_location: 'Location',
      nav_trust: 'Trust Committee',
      nav_contact: 'Contact',
      nav_temple: 'The Temple',
      nav_tourism: 'Chittorgarh Fort',
      nav_book: 'Enquire Now',
      hero_title: 'Experience Spiritual Serenity at the Heart of Chittorgarh',
      hero_sub: 'Welcome to Jain Dharamsala, where tradition meets comfort. Enjoy a peaceful stay with modern amenities and authentic Jain cuisine.',
      book_checkin: 'Check In',
      book_checkout: 'Check Out',
      book_guests: 'Guests',
      book_btn: 'Check Availability',
      about_title: 'About Jain Dharamsala',
      about_history: 'History & Heritage',
      about_facilities: 'Our Facilities',
      amenities_title: 'Everything You Need',
      footer_address: 'Chittorgarh Fort Road, Chittorgarh, Rajasthan.',
      footer_contact: 'Contact',
      footer_tourism: 'Explore Chittorgarh',
      footer_links: 'Quick Links',
      amenity_rooms: 'Spacious Rooms',
      amenity_ac: 'Air Conditioning',
      amenity_water: 'Hot Water',
      amenity_dining: 'Dining Hall',
      amenity_wifi: 'Free Wi-Fi',
      amenity_parking: 'Parking Space',
      site_name: 'Jain Dharamsala',
      site_sub: 'Chittorgarh',
      copyright_rights: 'All rights reserved.',
      made_with: 'Made with',
      by: 'by',
      guest_1: '1 Person',
      guest_2: '2 Persons',
      guest_3: '3+ Persons',
      guest_family: 'Family Room',
      info_best_price: 'Best Price Guaranteed',
      info_verified: 'Verified Stay',
      info_jain_food: 'Jain Food Available',
      footer_copyright: 'Jain Dharamsala Chittorgarh. All rights reserved.',
      trust_title: 'Trust Committee',
      trust_subtitle: 'Members dedicated to the service of the society.',
      trust_president: 'President',
      trust_secretary: 'Secretary',
      trust_treasurer: 'Treasurer',
      trust_all_members: 'All Members',
      trust_col_sn: 'S.No.',
      trust_col_name: 'Name',
      trust_col_city: 'Village/City',
      trust_dr_al_jain: 'Dr. A. L. Jain',
      trust_rakesh_jain: 'Mr. Rakesh Kumar Jain',
      trust_kanhaiyalal: 'Mr. Kanhaiyalal Chhajed',
      trust_member_1: 'Mr. Nareshbhai Amritlalji Shah',
      trust_city_mumbai: 'Mumbai',
      trust_member_2: 'Mr. Kalpesh Bhai Vanmalidasji Shah',
      trust_city_ahmedabad: 'Ahmedabad',
      trust_member_3: 'Mr. Sushil Bhai Narendra Bhai Shah',
      trust_member_4: 'Mr. Mayank Bhai Praveenchand Ji Shah',
      trust_member_5: 'Mr. Sanjay Bhai Amritlal Ji Shah',
      trust_member_6: 'Mr. Anandilal Ji Nagauri',
      trust_city_chittorgarh: 'Chittorgarh',
      trust_member_7: 'Mr. Rakesh Kumar Ji Ghiya',
      trust_member_8: 'Mr. Shantilalji Rathore',
      trust_member_9: 'Mr. Jivraj Ji Khatod',
      trust_member_10: 'Mr. Manoharlalji Mehta',
      trust_member_11: 'Mr. K. M. Jain',
      trust_member_12: 'Mr. Onkar Singh Babel',
      trust_member_13: 'Mr. Mukesh Kumar Mahatma',
      trust_member_14: 'Mr. Praveen Jain',
      contact_title: 'Contact Us',
      contact_greeting: 'Jai Jinendra. Please feel free to reach out via phone or email.',
      contact_warning_title: 'Warning',
      contact_warning_text: '"Phone numbers of Jain Dharamsala, operated by Shri Jain Shwetambar Saatbees Devari Fort Tirtha Trust Chittorgarh, are listed differently on Google search every day. These numbers are wrongly changed by hackers. People who call on the numbers given by hackers are being cheated, so it is requested to all the people not to pay money for room booking on any number."',
      contact_info_title: 'Information',
      contact_info_text: 'Jain Shwetambar Vishranti Grah is available in front of the railway station with AC room facilities, catering and luxury services. There are also 9 rooms available at Chittorgarh Fort with regular catering and dining facilities.',
      contact_phone_primary: 'Primary Phone',
      contact_rajendra: 'Mr. Rajendra Kachhala',
      timeline_1946: '1946',
      timeline_1946_title: 'Land Acquisition',
      timeline_1946_desc: 'Land for the current Dharamsala complex was purchased under the vision of Acharya Sri Vijayaniti Surishwar Ji.',
      timeline_1948: '1948',
      timeline_1948_title: 'Initial Completion',
      timeline_1948_desc: 'Construction of 9 rooms, 6 cubicles, 1 hall, and 7 shops completed under Kalyanji Anandji Pedhi.',
      timeline_1992: '1992',
      timeline_1992_title: 'Trust Expansion',
      timeline_1992_desc: 'New trust board took over. Added 5 premium rooms, 1 hall, and a dining room.',
      timeline_1998: '1998',
      timeline_1998_title: 'Bhojanshala Opening',
      timeline_1998_desc: 'A massive 60x60 Bhojanshala (Dining Hall) was constructed at the Station Road location.',
      timeline_2003: '2003',
      timeline_2003_title: 'The Great Rejuvenation',
      timeline_2003_desc: 'Leadership under Sri Kanhaiyalal Mahatma added 35 new rooms (11 AC) and modernized the facility.',
      timeline_2009: '2009',
      timeline_2009_title: 'Fort Bhojanshala',
      timeline_2009_desc: 'The dining hall at Saat Bees Devri Temple on the Fort was completed for pilgrims staying on the hill.',
      timeline_today: 'Today',
      timeline_today_title: 'A Premier Sanctuary',
      timeline_today_desc: 'A modern, soulful destination for travelers and sacred events in the heart of Chittorgarh.',
      temple_title: 'Shri Shwetambar Saat Bees Deori Temple',
      temple_subtitle: 'A 15th-Century Architectural Marvel in the Crown of Chittorgarh',
      temple_hist_1: 'The Saat Bees Deori Temple is the most significant Jain pilgrimage site within the Chittorgarh Fort. Originally constructed in the 15th century, this temple complex is a masterpiece of marble carving and Jain architecture.',
      temple_hist_2: 'The name "Saat Bees" (7 and 20) refers to the 27 auxiliary shrines (Devris) that surround the main sanctum. Each shrine is beautifully carved, depicting the Tirthankaras and scenes from Jain mythology.',
      temple_arch_title: 'Divine Architecture',
      temple_arch_text: 'The temple features intricate "Jali" work, vaulted ceilings, and pillars that tell stories of devotion and precision. The main deity, Lord Adinath, presides over the sanctum in a serene marble idol.',
      temple_restoration_title: 'Restoration & Legacy',
      temple_restoration_text: 'The temple has been carefully preserved and restored by the Shri Shwetambar Saat Bees Devari Fort Tirtha Trust, ensuring that the ancient marble work remains a beacon of spirituality for future generations.',
      temple_legend_title: 'Legend & Lore',
      temple_legend_text: 'Local tradition whispers that the main idol of Lord Adinath was found buried under the fort walls, and the temple was built on the very spot where it was discovered. The 27 shrines represent the constellations (Nakshatras), aligning the spiritual realm with the celestial world.',
      temple_fact_1_title: '15th Century',
      temple_fact_1_text: 'Built during the reign of Rana Kumbha, a golden era of Rajasthani architecture.',
      temple_fact_2_title: '27 Shrines',
      temple_fact_2_text: 'Intricately carved auxiliary temples representing the 27 Tirthankaras and constellations.',
      temple_fact_3_title: 'White Marble',
      temple_fact_3_text: 'Pure Makrana marble that glows with a golden hue during sunset.',
      sewa_title: 'Sewa & Pooja Booking',
      sewa_desc: 'Pre-book religious ceremonies and meals.',
      sewa_navkarsi: 'Navkarsi (Breakfast)',
      sewa_bhojanshala: 'Bhojanshala (Full Meal)',
      sewa_pooja: 'Special Pooja',
      booking_confirm_msg: 'Booking request submitted successfully!',
      temple_new_heritage_title: 'Our Heritage',
      temple_new_quote: '"Landing on this sacred land of Chittorgarh is the beginning of a celestial journey, where legends and enchanting architecture echo."',
      temple_new_p1: 'Situated near the Fateh Prakash Palace within Chittorgarh Fort, the Saat Bees Deori Temple is a group of twenty-seven temples dedicated to the Jain Tirthankaras. Established in the 11th century CE, entering this sacred land of Chittorgarh through the presence of the Jain community marks the beginning of an ethereal journey, resonating with legends and captivating architecture.',
      temple_new_p2: 'According to legend, the Saat Bees Deori Temple was originally a complex of twenty-seven Jain temples. As you approach the temple entrance, a sense of anticipation steadily grows. Step inside and prepare to be embraced by a calm and cool atmosphere, where sunlight filtering through intricately carved windows creates a gentle shimmer on the polished floors. The corridors are lined with impressive pillars adorned with detailed depictions of Jain deities. A serene sense of devotion permeates the air, inspiring visitors to further explore the temple’s wonders.',
      temple_new_p3: 'The architecture presents a fascinating blend of Jain and Maru-Gurjara styles. To fully appreciate the fine craftsmanship and majestic grandeur, one can lift their gaze toward the beautifully detailed ceilings. Chittorgarh Fort has been declared a UNESCO World Heritage Site.',
      temple_new_p4: 'Dedicated to the Tirthankaras—revered enlightened souls believed to guide seekers on the path of spiritual liberation—the temple’s central sanctum houses a magnificent idol of Lord Adinath, worshipped as the first Tirthankara. Seated in a tranquil meditative posture, the idol creates an atmosphere of peace and serenity. Standing reverently before this divine figure inspires reflection on the profound Jain principles of Ahimsa (non-violence), Saatya (truth), and Vairagya (detachment from worldly desires).',
      temple_new_p5: 'Within the temple complex, smaller shrines pay homage to other Tirthankaras, each adorned with intricate carvings and decorated with vibrant flowers offered by devoted worshippers. A visit to this temple not only allows one to witness architectural marvels but also offers a direct connection with Jain culture and spirituality.',
      temple_new_p6: 'Chittorgarh Fort, a place echoing countless tales of valor and resilience passed down through generations, warmly awaits your visit.',
      temple_sec1_title: 'Ancient Origin',
      temple_sec1_text: 'The Saat Bees Deori Temple was established in the 11th century AD as a grand complex of twenty-seven Jain temples. Built during the reign of Rajput rulers, this sacred site represents the pinnacle of medieval Jain architecture and devotion.',
      temple_sec2_title: 'Architectural Marvel',
      temple_sec2_text: 'The temple displays an excellent blend of Jain and Maru-Gurjara architectural styles. Each surface is adorned with intricate carvings of geometric patterns, floral motifs, and divine images, showcasing the extraordinary craftsmanship of ancient artisans.',
      temple_sec3_title: 'Sacred Idols',
      temple_sec3_text: 'The temple houses grand idols of twenty-four Tirthankaras, each meticulously carved in detail. The central sanctum features the idol of Lord Adinath in serene meditation, inspiring devotees with the profound principles of Ahimsa, Satya, and Vairagya.',
      temple_sec4_title: 'Ornate Pillars',
      temple_sec4_text: 'The temple corridors are decorated with impressive pillars, each a masterpiece of stone carving. These pillars depict intricate narratives from Jain deities, divine beings, and Jain scriptures, creating an atmosphere of divine reverence.',
      temple_sec5_title: 'Divine Ceiling',
      temple_sec5_text: 'The temple ceilings feature breathtaking mandala designs and geometric patterns representing the cosmic order. These intricate dome carvings showcase mathematical precision and spiritual symbolism, inviting visitors to contemplate the infinite.',
      temple_sec6_title: 'Divine Sanctum',
      temple_sec6_text: 'The main sanctum serves as the spiritual heart of the temple complex. Here, devotees offer prayers and flowers to the Tirthankaras, experiencing a deep connection with Jain philosophy and the path of spiritual liberation.',
      temple_new_loc_label: 'Location',
      temple_new_loc_val: 'Chittorgarh Fort, Rajasthan',
      temple_new_her_label: 'Heritage',
      temple_new_her_val: 'Saat Bees Deori Temple',
      temple_heritage_subtitle: 'A journey through time',
      temple_sec1_badge: '11th Century AD',
      temple_sec2_badge: 'Maru-Gurjara Style',
      temple_sec3_badge: 'Tirthankara Idols',
      temple_sec4_badge: 'Detailed Craftsmanship',
      temple_sec5_badge: 'Geometric Perfection',
      temple_sec6_badge: 'Spiritual Center',
      cal_dharmic_title: 'Dharmic Calendar',
      cal_dharmic_subtitle: 'Sacred Tithis & Bhojanshala Timings',
      cal_ashtami: 'Ashtami',
      cal_chaturdashi: 'Chaturdashi',
      cal_kalyanak: 'Tirthankar Kalyanaks',
      cal_timing_bhojan: 'Bhojanshala: 10:00 AM - 1:00 PM',
      cal_timing_navkarsi: 'Navkarsi: 8:00 AM - 9:30 AM',
      cal_timing_special: 'Special Rasoi',
      cal_view_details: 'View Sacred Details',
      
      // History Page
      history_title: 'History and Glorious Heritage',
      history_subtitle: 'The Eternal Saga of Chittaurgarh',
      history_quote: '"In history, the name Chittorgarh evokes glorious images of heroes like Maharana Pratap, Sanga, and Kumbha; the supreme devotee Meera Bai; the great philanthropist Bhamashah; the righteous Karmashah; and great scholars like Acharya Haribhadra. This is the holy land of Chitrakoot, where the splendor of Jain pride is preserved alongside power and devotion for centuries."',
      history_intro: 'This holy land of Chittorgarh is a magnificent confluence of power, devotion, and Jain splendor, where centuries of history are inscribed on stone walls.',
      
      // Timeline
      history_t1_year: '300 BCE',
      history_t1_title: 'Rise of Madhyamika',
      history_t1_desc: 'Arya Parivartan made Madhyamika (Nagari) his center during the reign of Ashoka\'s grandson, Samprati.',
      
      history_t2_year: '4th Century',
      history_t2_title: 'Capital of Shrijanpad',
      history_t2_desc: 'Madhyamika Nagari, the capital of Shrijanpad since the Mahabharata era, was at its peak.',
      
      history_t3_year: '947 CE',
      history_t3_title: 'Arrival of Simandar Shah',
      history_t3_desc: 'Simandar Shah started trade in Kerapurpattan and acquired immense wealth through fortune.',
      
      history_t4_year: '972 CE',
      history_t4_title: 'Panch Tirth Consecration',
      history_t4_desc: 'Grand consecration of five pilgrimages including Chittorgarh under Acharya Yashobhadra Suri.',
      
      history_t5_year: '1175 CE',
      history_t5_title: 'Shantinath Temple',
      history_t5_desc: 'Construction of the artistic Lord Shantinath temple near Ratneshwar Lake.',
      
      history_t6_year: '1448 CE',
      history_t6_title: 'Bhandari Vella\'s Contribution',
      history_t6_desc: 'Construction of the Northern Parshvanath Temple by Bhandari Shreshthi Vella.',
      
      history_t7_year: '1530 CE',
      history_t7_title: 'Era of Karmashah Doshi',
      history_t7_desc: 'Grand construction of the Southern Parshvanath Temple by Karmashah Doshi.',
      
      history_t8_year: '1973 CE',
      history_t8_title: 'Haribhadrasuri Memorial',
      history_t8_desc: 'Consecration of the memorial temple of Acharya Haribhadrasuri, author of 1444 texts.',
      
      // Categories
      history_cat_fort: 'Fort Temples',
      history_cat_city: 'City Shwetamber Temples',
      history_cat_digambar: 'Digambar Jain Temples',
      history_cat_monuments: 'Monuments',
      
      // Temple Details
      history_fort_t1_name: '1. Shri Saat Bees Deori Temple Complex',
      history_fort_t1_desc: 'Surrounded by 27 shrines, this magnificent temple complex witnesses the spiritual simplicity and rich ornamentation of Jain architecture.',
      history_fort_t1_year: '972 CE (Consecration)',
      history_fort_t2_name: '2. Northern Parshvanath Temple',
      history_fort_t2_desc: 'Built by Bhandari Shreshthi Vella, this temple is famous for its fine craftsmanship and idols of great Acharyas.',
      history_fort_t2_year: '1448 CE',
      history_fort_t3_name: '3. Southern Parshvanath Temple',
      history_fort_t3_desc: 'Built by Talashah and his son Karmashah Doshi, this temple symbolizes devotion and sacrifice.',
      history_fort_t3_year: '1530 CE',
      history_fort_t4_name: '4. Shantinath and Mahavir Swami Temples',
      history_fort_t4_desc: 'Located near Ratneshwar Lake, these temples are known for their antiquity and serene atmosphere.',
      history_fort_t4_year: '1175 - 1444 CE',
      
      history_city_t1_name: '4. Shri Rishabhdev Temple (Dhimo Temple)',
      history_city_t1_desc: 'Located at the foot of the fort, this temple was built with devotion by the Shravaks of the "Dhig" gotra.',
      history_city_t1_year: '400 Years Old',
      history_city_t2_name: '5. Shri Haribhadrasuri Memorial Temple',
      history_city_t2_desc: 'Built in the holy memory of the great philosopher Acharya Haribhadrasuri, this temple is a center of knowledge and detachment.',
      history_city_t2_year: '1973 CE',
      history_city_t3_name: '6. Chaumukha Parshvanath Temple',
      history_city_t3_desc: 'Located near Gaumukh Kund, this temple is famous for its unique stone craft and Kannada inscriptions.',
      history_city_t3_year: '1491 VS',
      
      history_digambar_t1_name: '9. Shri Mallinath Bhagwan Temple (Mahavir Prasad)',
      history_digambar_t1_desc: 'Located near Kirti Stambh, this temple reflects the ancient glory of the Digambar tradition.',
      history_digambar_t1_year: '1428 CE',
      history_digambar_t2_name: '11. Shri Suparshvanath Digambar Jain Temple',
      history_digambar_t2_desc: 'This beautiful temple of modern architecture is a major center for the religious activities of the Digambar Jain community.',
      history_digambar_t2_year: '2005 CE',

      history_mon_t1_name: '13. Kirti Stambh (Tower of Fame)',
      history_mon_t1_desc: 'This 75-foot tall, seven-story tower dedicated to Lord Adinath is a world-famous example of Jain architecture.',
      history_mon_t1_year: '11th - 12th Century',

      history_footer_text: 'Magnificent examples of Jain architecture. This is a brief description of the main temples. There are many more historical Jain temples in Chittorgarh that represent our rich heritage.',
    },
    hi: {
      nav_home: 'होम',
      nav_about: 'हमारे बारे में',
      nav_history: 'इतिहास',
      nav_rooms: 'कमरे',
      nav_amenities: 'सुविधाएं',
      nav_location: 'स्थान',
      nav_trust: 'ट्रस्ट समिति',
      nav_contact: 'संपर्क',
      nav_temple: 'मंदिर',
      nav_tourism: 'चित्तौड़गढ़ किला',
      nav_book: 'पूछताछ करें',
      hero_title: 'चित्तौड़गढ़ के केंद्र में आध्यात्मिक शांति का अनुभव करें',
      hero_sub: 'जैन धर्मशाला में आपका स्वागत है, जहाँ परंपरा और आराम का मिलन होता है। आधुनिक सुविधाओं और प्रमाणिक जैन भोजन के साथ शांतिपूर्ण प्रवास का आनंद लें।',
      book_checkin: 'चेक इन',
      book_checkout: 'चेक आउट',
      book_guests: 'अतिथि',
      book_btn: 'उपलब्धता जांचें',
      about_title: 'जैन धर्मशाला के बारे में',
      about_history: 'इतिहास और विरासत',
      about_facilities: 'हमारी सुविधाएं',
      amenities_title: 'आपकी ज़रूरत की हर चीज़',
      footer_address: 'चित्तौड़गढ़ किला रोड, चित्तौड़गढ़, राजस्थान।',
      footer_contact: 'संपर्क',
      footer_tourism: 'चित्तौड़गढ़ घूमें',
      footer_links: 'त्वरित लिंक',
      amenity_rooms: 'हवादार कमरे',
      amenity_ac: 'वातानुकूलित',
      amenity_water: 'गर्म पानी',
      amenity_dining: 'भोजनशाला',
      amenity_wifi: 'फ्री वाई-फाई',
      amenity_parking: 'पार्किंग स्थल',
      site_name: 'जैन धर्मशाला',
      site_sub: 'चित्तौड़गढ़',
      copyright_rights: 'सर्वाधिकार सुरक्षित।',
      made_with: 'निर्मित',
      by: 'द्वारा',
      guest_1: '1 व्यक्ति',
      guest_2: '2 व्यक्ति',
      guest_3: '3+ व्यक्ति',
      guest_family: 'पार्िवारिक कमरा',
      info_best_price: 'सर्वोत्तम मूल्य की गारंटी',
      info_verified: 'सत्यापित प्रवास',
      info_jain_food: 'जैन भोजन उपलब्ध',
      footer_copyright: 'जैन धर्मशाला चित्तौड़गढ़। सर्वाधिकार सुरक्षित।',
      trust_title: 'ट्रस्ट समिति',
      trust_subtitle: 'समाज की सेवा को समर्पित सदस्य।',
      trust_president: 'अध्यक्ष',
      trust_secretary: 'सचिव',
      trust_treasurer: 'कोषाध्यक्ष',
      trust_all_members: 'सभी सदस्य',
      trust_col_sn: 'क्र.सं.',
      trust_col_name: 'नाम',
      trust_col_city: 'गाँव/शहर',
      trust_dr_al_jain: 'डॉ ए. एल. जैन',
      trust_rakesh_jain: 'श्री राकेश कुमार जैन',
      trust_kanhaiyalal: 'श्री कन्हैयालाल छाजेड़',
      trust_member_1: 'श्री नरेशभाई अमृतलालजी शाह',
      trust_city_mumbai: 'मुम्बई',
      trust_member_2: 'श्री कल्पेश भाई वनमालीदासजी शाह',
      trust_city_ahmedabad: 'अहमदाबाद',
      trust_member_3: 'श्री सुशील भाई नरेन्द्र भाई शाह',
      trust_member_4: 'श्री मयंक भाई प्रवीणचन्द जी शाह',
      trust_member_5: 'श्री संजय भाई अमृतलाल जी शाह',
      trust_member_6: 'श्री आन्नदीलाल जी नागौरी',
      trust_city_chittorgarh: 'चित्तौड़गढ़',
      trust_member_7: 'श्री राकेश कुमार जी घीया',
      trust_member_8: 'श्री शांतीलालजी राठौड़',
      trust_member_9: 'श्री जीवराज जी खटोड़',
      trust_member_10: 'श्री मनोहरलालजी मेहता',
      trust_member_11: 'श्री के. एम. जैन',
      trust_member_12: 'श्री औंकार सिंह बाबेल',
      trust_member_13: 'श्री मुकेश कुमार महात्मा',
      trust_member_14: 'श्री प्रवीण Jain',
      contact_title: 'संपर्क करें',
      contact_greeting: 'जय जिनेन्द्र। कृपया पधारें या ईमेल के माध्यम से संपर्क करें।',
      contact_warning_title: 'चेतावनी',
      contact_warning_text: '"श्री जैन श्वेताम्बर सातबीस देवरी किला तीर्थ ट्रस्ट चित्तौड़गढ़ द्वारा संचालित जैन धर्मशाला को फोन नम्बर गूगल सर्च पर रोज अलग अलग नम्बर लिखा हुआ है। यह नम्बर गलत तरीके से हैकर द्वारा बदला गया है। जो लोग हैकर द्वारा दिए गये नम्बर पर रूम बुकिंग के लिए फोन करते है उनके साथ धोखाधड़ी हो रही है, इसलिए सभी लोगो से निवेदन है कि किसी भी नम्बर पर बुकिंग के लिए रुपयों का भुगतान ना करें"',
      contact_info_title: 'सूचना',
      contact_info_text: 'जैन श्वेताम्बर विश्रान्ति गृह रेलवे स्टेशन के सामने चित्तौड़गढ़ में एसी सुविधा वाले कमरों के साथ नवकारसी एवं भोजनशाला की अत्युत्तम सुविधा उपलब्ध है। चित्तौड़गढ़ किले पर भी 9 कमरे व नियमित नवकारसी एवं भोजनशाला की सुविधा उपलब्ध है।',
      contact_phone_primary: 'प्रायमरी फोन',
      contact_rajendra: 'श्री राजेन्द्र कच्छाला',
      timeline_1946: '1946',
      timeline_1946_title: 'भूमि अधिग्रहण',
      timeline_1946_desc: 'आचार्य श्री विजयनीति सूरीश्वर जी म.सा. की प्रेरणा से वर्तमान धर्मशाला परिसर की भूमि क्रय की गई।',
      timeline_1948: '1948',
      timeline_1948_title: 'प्रथम निर्माण पूर्ण',
      timeline_1948_desc: '9 कमरे, 6 कोठरियाँ, 1 हाॅल व 7 दुकानों का निर्माण कार्य पूर्ण हुआ।',
      timeline_1992: '1992',
      timeline_1992_title: 'ट्रस्ट विस्तार',
      timeline_1992_desc: 'नये ट्रस्ट मंडल ने कार्यभार संभाला। 5 कमरे, 1 हाल व भोजनशाला का निर्माण कराया गया।',
      timeline_1998: '1998',
      timeline_1998_title: 'भोजनशाला शुभारंभ',
      timeline_1998_desc: 'स्टेशन रोड पर 60x60 क्षेत्रफल की विशाल एवं सुंदर भोजनशाला का निर्माण पूर्ण हुआ।',
      timeline_2003: '2003',
      timeline_2003_title: 'कायाकल्प अभियान',
      timeline_2003_desc: 'श्री कन्हैयालाल जी महात्मा के नेतृत्व में 35 नये कमरों (11 ए.सी.) की अभिवृद्धि हुई।',
      timeline_2009: '2009',
      timeline_2009_title: 'किला भोजनशाला',
      timeline_2009_desc: 'सात बीस देवरी मंदिर (किला) में भोजनशाला का कार्य संपन्न हुआ एवं नियमित रूप से चालू हुई।',
      timeline_today: 'आज',
      timeline_today_title: 'नगर की श्रेष्ठ व्यवस्था',
      timeline_today_desc: 'नगर की श्रेष्ठ व्यवस्थाओं वाली जगह, जो यात्रिगणों के साथ विवाह और सामाजिक आयोजनों के लिए प्रसिद्ध है।',
      temple_title: 'श्री श्वेताम्बर सात बीस देवरी मंदिर',
      temple_subtitle: 'चित्तौड़गढ़ के मुकुट में 15वीं शताब्दी का स्थापत्य चमत्कार',
      temple_hist_1: 'सात बीस देवरी मंदिर चित्तौड़गढ़ किले के भीतर सबसे महत्वपूर्ण जैन तीर्थ स्थल है। मूल रूप से 15वीं शताब्दी में निर्मित, यह मंदिर परिसर संगमरमर की नक्काशी और जैन वास्तुकला का एक उत्कृष्ट नमूना है।',
      temple_hist_2: '"सात बीस" (7 और 20) नाम मुख्य गर्भगृह के चारों ओर स्थित 27 सहायक मंदिरों (देवरी) को संदर्भित करता है। प्रत्येक देवरी को खूबसूरती से उकेरा गया है, जिसमें तीर्थंकरों और जैन पौराणिक कथाओं के दृश्यों को दर्शाया गया है।',
      temple_arch_title: 'दिव्य वास्तुकला',
      temple_arch_text: 'मंदिर में जटिल "जाली" का काम, गुंबददार छतें और स्तंभ हैं जो भक्ति और सटीकता की कहानियां सुनाते हैं। मुख्य देवता, भगवान आदिनाथ, गर्भगृह में एक शांत संगमरमर की मूर्ति में विराजमान हैं।',
      temple_restoration_title: 'जीर्णोद्धार और विरासत',
      temple_restoration_text: 'मंदिर को श्री श्वेताम्बर सात बीस देवरी किला तीर्थ ट्रस्ट द्वारा सावधानीपूर्वक संरक्षित और पुनर्स्थापित किया गया है, जिससे यह सुनिश्चित होता है कि प्राचीन संगमरमर का काम भविष्य की पीढ़ियों के लिए आध्यात्मिकता का प्रतीक बना रहे।',
      temple_legend_title: 'किंवदंती और कथा',
      temple_legend_text: 'स्थानीय परंपरा कहती है कि भगवान आदिनाथ की मुख्य मूर्ति किले की दीवारों के नीचे दबी हुई मिली थी, और मंदिर उसी स्थान पर बनाया गया था जहाँ वह मिली थी। 27 देवरियां नक्षत्रों का प्रतिनिधित्व करती हैं, जो आध्यात्मिक जगत को खगोलीय दुनिया के साथ जोड़ती हैं।',
      temple_fact_1_title: '15वीं शताब्दी',
      temple_fact_1_text: 'राणा कुंभा के शासनकाल के दौरान निर्मित, जो राजस्थानी वास्तुकला का स्वर्ण युग था।',
      temple_fact_2_title: '27 देवरियां',
      temple_fact_2_text: '27 तीर्थंकरों और नक्षत्रों का प्रतिनिधित्व करने वाले जटिल नक्काशीदार सहायक मंदिर।',
      temple_fact_3_title: 'सफेद संगमरमर',
      temple_fact_3_text: 'शुद्ध मकराना संगमरमर जो सूर्यास्त के दौरान सुनहरी आभा के साथ चमकता है।',
      sewa_title: 'सेवा और पूजा बुकिंग',
      sewa_desc: 'धार्मिक समारोहों और भोजन की अग्रिम बुकिंग करें।',
      sewa_navkarsi: 'नवकारसी (नाश्ता)',
      sewa_bhojanshala: 'भोजनशाला (पूर्ण भोजन)',
      sewa_pooja: 'विशेष पूजा',
      booking_confirm_msg: 'बुकिंग अनुरोध सफलतापूर्वक सबमिट किया गया!',
      temple_new_heritage_title: 'हमारी विरासत',
      temple_new_quote: '"चित्तौड़गढ़ की इस पावन धरा पर आगमन एक अलौकिक यात्रा की शुरुआत है, जहाँ किंवदंतियों और मनमोहक वास्तुकला की गूँज सुनाई देती है।ें"',
      temple_new_p1: 'चित्तौड़गढ़ किले में फतेहप्रकाश महल के पास स्थित सात बीस देवरी जैन मंदिर, जैन तीर्थंकरों को समर्पित सत्ताईस मंदिरों का एक समूह है। 11वीं सदी ईस्वी में स्थापित जैन समुदाय चित्तौड़गढ़ की पवित्र भूमि में प्रवेश करना, मिथकों, मनमोहक वास्तुकला की गूँज के माध्यम से एक अलौकिक यात्रा की शुरुआत है। किंवदंती के अनुसार, सात बीस देवरी मंदिर, मूल रूप से सत्ताईस जैन मंदिरों का एक समूह है।',
      temple_new_p2: 'जैसे-जैसे आप मंदिर के दरवाज़े के करीब पहुँचते हैं, उम्मीद की भावना बढ़ती जाती है। अंदर प्रवेश करें और शांत, ठंडे माहौल से घिरने के लिए तैयार हो जाएँ, नक्काशीदार खिड़कियों से छनकर आती सूरज की रोशनी पॉलिश किए हुए फर्श पर एक हल्की चमक पैदा करती है। गलियारों में प्रभावशाली खंभे हैं जो जैन देवताओं के विस्तृत चित्रण से सजे हुए हैं। हवा में ही एक शांत भक्ति गूँज रही है जो आपको मंदिर के चमत्कार को और अधिक खोजने के लिए प्रेरित करती है।',
      temple_new_p3: 'वास्तुकला जैन और मारू-गुर्जर शैलियों का एक दिलचस्प मिश्रण है। शिल्प कौशल के बारीक विवरण और विशाल भव्यता की पूरी तरह से सराहना करने के लिए अपनी आँखें छत की ओर उठा सकते हैं। चित्तौड़गढ़ किले को यूनेस्को द्वारा विश्व धरोहर स्थल घोषित किया गया है।',
      temple_new_p4: 'तीर्थंकरों को समर्पित, पूजनीय प्रबुद्ध आत्माएं जिन्हें आध्यात्मिक मुक्ति के मार्ग पर साधकों का मार्गदर्शन करने का श्रेय दिया जाता है, मंदिर के केंद्रीय गर्भगृह में भगवान आदिनाथ की एक शानदार मूर्ति है, जिन्हें पहले तीर्थंकर के रूप में पूजा जाता है। शांत, ध्यान मुद्रा में स्थित यह मूर्ति मानसिक शांति और सुकून का माहौल बनाती है। इस दिव्य मूर्ति के सामने श्रद्धा से रुककर, व्यक्ति को अहिंसा (अहिंसा), सत्य (सच्चाई), और वैराग्य (मोह-माया से मुक्ति) के गहरे जैन सिद्धांतों पर विचार करने की प्रेरणा मिलती है।',
      temple_new_p5: 'मंदिर परिसर के अंदर आस-पास के छोटे मंदिर अन्य तीर्थंकरों को श्रद्धांजलि देते हैं, हर मंदिर जटिल नक्काशीदार आकृतियों से सजा हुआ है और समर्पित भक्तों द्वारा चढ़ाए गए जीवंत फूलों से सुशोभित है।',
      temple_new_p6: 'मंदिर की यात्रा आपको वास्तुकला के चमत्कारों को देखने के साथ-साथ जैन संस्कृति से सीधे जुड़ने का अवसर देती है। चित्तौड़गढ़ का किला जहाँ वीरता और दृढ़ता की कई कहानियाँ हैं जो पीढ़ियों से चली आ रही हैं पर पधारे हम आपका इंतजार कर रहे है।',
      temple_sec1_title: 'प्राचीन उत्पत्ति',
      temple_sec1_text: 'सात बीस देवरी मंदिर की स्थापना 11वीं शताब्दी ईस्वी में सत्ताईस जैन मंदिरों के एक भव्य परिसर के रूप में की गई थी। राजपूत शासकों के शासनकाल के दौरान निर्मित, यह पवित्र स्थल मध्यकालीन जैन वास्तुकला और भक्ति के शिखर का प्रतिनिधित्व करता है।',
      temple_sec2_title: 'वास्तुकला का चमत्कार',
      temple_sec2_text: 'मंदिर जैन और मारू-गुर्जर वास्तुकला शैलियों का एक उत्कृष्ट मिश्रण प्रदर्शित करता है। प्रत्येक सतह ज्यामितीय पैटर्न, पुष्प रूपांकनों और दिव्य चित्रों की जटिल नक्काशी से सुशोभित है, जो प्राचीन कारीगरों की असाधारण शिल्प कौशल को प्रदर्शित करती है।',
      temple_sec3_title: 'पवित्र मूर्तियां',
      temple_sec3_text: 'मंदिर में चौबीस तीर्थंकरों की भव्य मूर्तियां हैं, प्रत्येक को सावधानीपूर्वक विस्तार से उकेरा गया है। केंद्रीय गर्भगृह में शांत ध्यान में भगवान आदिनाथ की मूर्ति है, जो भक्तों को अहिंसा, सत्य और वैराग्य के गहन सिद्धांतों से प्रेरित करती है।',
      temple_sec4_title: 'अलंकृत स्तंभ',
      temple_sec4_text: 'मंदिर के गलियारे प्रभावशाली स्तंभों से सुसज्जित हैं, प्रत्येक पत्थर की नक्काशी की एक उत्कृष्ट कृति है। ये स्तंभ जैन देवताओं, दिव्य प्राणियों और जैन शास्त्रों से जटिल कथाओं को दर्शाते हैं, जो दिव्य श्रद्धा का वातावरण बनाते हैं।',
      temple_sec5_title: 'दिव्य छत',
      temple_sec5_text: 'मंदिर की छतों में लुभावनी मंडल डिजाइन और ज्यामितीय पैटर्न हैं जो ब्रह्मांडीय व्यवस्था का प्रतिनिधित्व करते हैं। ये जटिल गुंबद नक्काशी गणितीय सटीकता और आध्यात्मिक प्रतीकवाद को प्रदर्शित करती हैं, आगंतुकों को अनंत पर चिंतन करने के लिए आमंत्रित करती हैं।',
      temple_sec6_title: 'दिव्य गर्भगृह',
      temple_sec6_text: 'मुख्य गर्भगृह मंदिर परिसर के आध्यात्मिक हृदय के रूप में कार्य करता है। यहां, भक्त तीर्थंकरों को प्रार्थना और फूल अर्पित करते हैं, जैन दर्शन और आध्यात्मिक मुक्ति के मार्ग के साथ एक गहरा संबंध अनुभव करते हैं।',
      temple_new_loc_label: 'स्थान',
      temple_new_loc_val: 'चित्तौड़गढ़ किला, राजस्थान',
      temple_new_her_label: 'विरासत',
      temple_new_her_val: 'सात बीस देवरी मंदिर',
      temple_heritage_subtitle: 'समय के माध्यम से एक यात्रा',
      temple_sec1_badge: '11वीं शताब्दी ईस्वी',
      temple_sec2_badge: 'मारू-गुर्जर शैली',
      temple_sec3_badge: 'तीर्थंकर मूर्तियां',
      temple_sec4_badge: 'विस्तृत शिल्प कौशल',
      temple_sec5_badge: 'ज्यामितीय पूर्णता',
      temple_sec6_badge: 'आध्यात्मिक केंद्र',
      cal_dharmic_title: 'धार्मिक कैलेंडर',
      cal_dharmic_subtitle: 'पवित्र तिथियां और भोजनशाला का समय',
      cal_ashtami: 'अष्टमी',
      cal_chaturdashi: 'चतुर्दशी',
      cal_kalyanak: 'तीर्थंकर कल्याणक',
      cal_timing_bhojan: 'भोजनशाला: प्रातः 10:00 - दोपहर 1:00',
      cal_timing_navkarsi: 'नवकारसी: प्रातः 8:00 - 9:30',
      cal_timing_special: 'विशेष रसोई',
      cal_view_details: 'पवित्र विवरण देखें',

      // History Page
      history_title: 'इतिहास और गौरवशाली विरासत',
      history_subtitle: 'चित्तौड़गढ़ की शाश्वत गाथा',
      history_quote: '"इतिहास में, चित्तौड़गढ़ का नाम महाराणा प्रताप, सांगा और कुंभा जैसे नायकों; परम भक्त मीरा बाई; महान परोपकारी भामाशाह; धर्मी कर्मशाह; और आचार्य हरिभद्र जैसे महान विद्वानों की गौरवशाली यादें ताजा कर देता है। चित्तौड़गढ़ की यह पावन धरा शक्ति, भक्ति और जैन वैभव का एक शानदार संगम है, जहाँ सदियों का इतिहास पत्थर की दीवारों पर अंकित है।ें"',
      history_intro: 'चित्तौड़गढ़ की यह पावन धरा शक्ति, भक्ति और जैन वैभव का एक शानदार संगम है, जहाँ सदियों का इतिहास पत्थर की दीवारों पर अंकित है।',

      // Timeline
      history_t1_year: '300 ई.पू.',
      history_t1_title: 'माध्यमिका का उदय',
      history_t1_desc: 'आर्य परिवर्तन ने सम्राट अशोक के पौत्र संप्रति के शासनकाल के दौरान माध्यमिका (नगरी) को अपना केंद्र बनाया।',

      history_t2_year: '4वीं शताब्दी',
      history_t2_title: 'श्रीजनपद की राजधानी',
      history_t2_desc: 'महाभारत काल से श्रीजनपद की राजधानी रही माध्यमिका नगरी अपने शिखर पर थी।',

      history_t3_year: '947 ईस्वी',
      history_t3_title: 'सिमंदर शाह का आगमन',
      history_t3_desc: 'सिमंदर शाह ने केरापुरपत्तन में व्यापार शुरू किया और भाग्य के माध्यम से अपार धन अर्जित किया।',

      history_t4_year: '972 ईस्वी',
      history_t4_title: 'पंच तीर्थ प्रतिष्ठा',
      history_t4_desc: 'आचार्य यशोभद्र सूरी के सानिध्य में चित्तौड़गढ़ सहित पांच तीर्थों की भव्य प्रतिष्ठा हुई।',

      history_t5_year: '1175 ईस्वी',
      history_t5_title: 'शांतिनाथ मंदिर',
      history_t5_desc: 'रत्नेश्वर झील के पास कलात्मक भगवान शांतिनाथ मंदिर का निर्माण।',

      history_t6_year: '1448 ईस्वी',
      history_t6_title: 'भंडारी वेल्ला का योगदान',
      history_t6_desc: 'भंडारी श्रेष्ठी वेल्ला द्वारा उत्तरी पार्श्वनाथ मंदिर का निर्माण।',

      history_t7_year: '1530 ईस्वी',
      history_t7_title: 'कर्मशाह दोशी का युग',
      history_t7_desc: 'कर्मशाह दोशी द्वारा दक्षिणी पार्श्वनाथ मंदिर का भव्य निर्माण।',

      history_t8_year: '1973 ईस्वी',
      history_t8_title: 'हरिभद्रसूरी स्मारक',
      history_t8_desc: '1444 ग्रंथों के रचयिता आचार्य हरिभद्रसूरी के स्मारक मंदिर की प्रतिष्ठा।',

      // Categories
      history_cat_fort: 'किले के मंदिर',
      history_cat_city: 'शहर के श्वेतांबर मंदिर',
      history_cat_digambar: 'दिगंबर जैन मंदिर',
      history_cat_monuments: 'स्मारक',

      // Temple Details
      history_fort_t1_name: '1. श्री सात बीस देवरी मंदिर परिसर',
      history_fort_t1_desc: '27 तीर्थों से घिरा, यह शानदार मंदिर परिसर जैन वास्तुकला की आध्यात्मिक सादगी और समृद्ध अलंकरण का गवाह है।',
      history_fort_t1_year: '972 ईस्वी (प्रतिष्ठा)',
      history_fort_t2_name: '2. उत्तरी पार्श्वनाथ मंदिर',
      history_fort_t2_desc: 'भंडारी श्रेष्ठी वेल्ला द्वारा निर्मित, यह मंदिर अपनी बेहतरीन शिल्प कौशल और महान आचार्यों की मूर्तियों के लिए प्रसिद्ध है।',
      history_fort_t2_year: '1448 ईस्वी',
      history_fort_t3_name: '3. दक्षिणी पार्श्वनाथ मंदिर',
      history_fort_t3_desc: 'तालाशाह और उनके पुत्र कर्मशाह दोशी द्वारा निर्मित, यह मंदिर भक्ति और त्याग का प्रतीक है।',
      history_fort_t3_year: '1530 ईस्वी',
      history_fort_t4_name: '4. शांतिनाथ और महावीर स्वामी मंदिर',
      history_fort_t4_desc: 'रत्नेश्वर झील के पास स्थित, ये मंदिर अपनी प्राचीनता और शांत वातावरण के लिए जाने जाते हैं।',
      history_fort_t4_year: '1175 - 1444 ईस्वी',

      history_city_t1_name: '4. श्री ऋषभदेव मंदिर (धीमो मंदिर)',
      history_city_t1_desc: 'किले की तलहटी में स्थित, यह मंदिर "धिग" गोत्र के श्रावकों द्वारा भक्ति के साथ बनाया गया था।',
      history_city_t1_year: '400 साल पुराना',
      history_city_t2_name: '5. श्री हरिभद्रसूरी स्मारक मंदिर',
      history_city_t2_desc: 'महान दार्शनिक आचार्य हरिभद्रसूरी की पावन स्मृति में निर्मित, यह मंदिर ज्ञान और वैराग्य का केंद्र है।',
      history_city_t2_year: '1973 ईस्वी',
      history_city_t3_name: '6. चौमुखा पार्श्वनाथ मंदिर',
      history_city_t3_desc: 'गौमुख कुंड के पास स्थित यह मंदिर अपनी अनूठी पत्थर शिल्प कला और कन्नड़ शिलालेखों के लिए प्रसिद्ध है।',
      history_city_t3_year: '1491 वि.सं.',

      history_digambar_t1_name: '9. श्री मल्लिनाथ भगवान मंदिर (महावीर प्रसाद)',
      history_digambar_t1_desc: 'कीर्ति स्तंभ के पास स्थित यह मंदिर दिगंबर परंपरा की प्राचीन महिमा को दर्शाता है।',
      history_digambar_t1_year: '1428 ईस्वी',
      history_digambar_t2_name: '11. श्री सुपार्श्वनाथ दिगंबर जैन मंदिर',
      history_digambar_t2_desc: 'आधुनिक वास्तुकला का यह सुंदर मंदिर दिगंबर जैन समुदाय की धार्मिक गतिविधियों का एक प्रमुख केंद्र है।',
      history_digambar_t2_year: '2005 ईस्वी',

      history_mon_t1_name: '13. कीर्ति स्तंभ (Tower of Fame)',
      history_mon_t1_desc: '75 फीट ऊंचा, सात मंजिला यह स्तंभ भगवान आदिनाथ को समर्पित है और जैन वास्तुकला का एक विश्व प्रसिद्ध उदाहरण है।',
      history_mon_t1_year: '11वीं - 12वीं शताब्दी',

      history_footer_text: 'जैन वास्तुकला के शानदार उदाहरण। यह मुख्य मंदिरों का संक्षिप्त विवरण है। चित्तौड़गढ़ में और भी कई ऐतिहासिक जैन मंदिर हैं जो हमारी समृद्ध विरासत का प्रतिनिधित्व करते हैं।',
    },
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
